### ISSUE TITLE
Screensaver only shows a blank screen...

### ISSUE THREAD

**Issue by gregdeichler** [eozh/PictureScreenSaver#1]
Hello. I tried downloading one of your releases, as well as building the screensaver using Xcode. It only shows a black screen and never any of the images. They are all JPG format. Do you have any ideas?

This app is perfect otherwise. All the options I needed. Thanks for your time.

**Comment by eozh** [comment]
Hi Greg,  Thank you for trying my screensaver. Could you share which version of MacOS you are running and a screenshot of your PictureScreenSaver configuration window and Finder window with images? Also, how many monitors do you have connected? 
I have a known issue with latest versions of macOS with multiple monitors. I wonder if it is related. 

Another possibility if it is security related. You can try giving “legacyScreenSaver” process Full Disk Access in the system settings. Here is the procedure from another screensaver:

https://www.jetsoncreative.com/screensaverplugin

Please let me know if it helps. In the meanwhile, I can recommend another free screensaver that can display slideshow of images: ArtSaver

https://user.informatik.uni-bremen.de/zach/software/ArtSaver/index.html

Eugene

**Comment by gregdeichler** [comment]
Thanks. I was trying to use it on Ventura, and Monterey. I eventually settled on using Catalina becuase that was the OS that was available around the time you released the screensaver. Catalina works perfectly. Thats a great point about full disk access. I'm mad i didnt think of that.

Thank you for the additional links also. ArtSaver looks great. Thanks again for all of your work, and assistance.
